### ISSUE TITLE
Separate cross-validation set (lasagne)

### ISSUE THREAD

**Issue by henridwyer** [dnouri/nolearn#68] opened 2015-04-09 23:27 UTC
In the lasagne module, the cross validation score is calculated by splitting the training data. However, for certain kinds of data it's necessary to use a separate cross validation set. 

Is this a feature you would like to add? How would you like this implemented?

I am suggesting:
- modify train_test_loop to take 5 arguments (self, X_train, y_train, X_valid, y_valid), 
- have fit handle the train test split, and then call fit_cv
- create a new fit_cv function that takes 2 more arguments (X_valid, y_valid) and basically does what fit does now

**Comment by fmfn** [comment] 2015-04-13 19:13
I came here to mention the exact same thing.

I was thinking of having X_valid, Y_valid as arguments of fit; both defaulting to None. If None is passed, fit carries on with no validation; if, instead, they are not none, validation is performed on the valid set.

CV could be implemented in another object, NeuralNet_CV for example, similar to how sklearn does (Ridge and Ridge_CV, etc.).

**Comment by dnouri** [comment] 2015-04-13 20:42
You should be able to pass the `eval_size=0.0` to `NeuralNet` and thus have it use no validation set.

If you need to control exactly which part of X and y will be used for training versus validation, there's the option to subclass and override the `train_test_split` method to return the exact split that you want.

Will these two options cover what you had in mind?

**Comment by fmfn** [comment] 2015-04-13 22:48
> If you need to control exactly which part of X and y will be used for training versus validation, there's the option to subclass and override the train_test_split method to return the exact split that you want.

Yes, this is what I've been using, I just thought it could be a bit more elegant though. But it works fine.

**Comment by alexjc** [comment] 2015-04-26 09:57
With `eval_size=0.0` the verbose mode prints some warnings, but otherwise it does work as intended.

**Comment by delphine108** [comment] 2015-04-26 10:50
I am sorry, but I don't understand why `eval_size=0.0` doesn't work for me 

With this code, I get a ZeroDivisionError:
```
net0 = NeuralNet(layers=layers0,
                 input_shape=(None, num_features),
                 dense0_num_units=372,                 
                 dropout_p=0.25,
                 dense1_num_units=372,                 
                 
                 output_num_units=num_classes,
                 output_nonlinearity=softmax,
                 
                 update=nesterov_momentum,
                 update_learning_rate=0.01,
                 update_momentum=0.9,                
                 
                 eval_size=0.0,
                 verbose=1,
                 max_epochs=20)
net0.fit(X,y)
```
Here is the error message:
```
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-24-767460c55f9b> in <module>()
----> 1 net0.fit(X, y)

C:\bin\Anaconda\lib\site-packages\nolearn\lasagne.pyc in fit(self, X, y)
    148 
    149         try:
--> 150             self.train_loop(X, y)
    151         except KeyboardInterrupt:
    152             pdb.set_trace()

C:\bin\Anaconda\lib\site-packages\nolearn\lasagne.pyc in train_loop(self, X, y)
    155     def train_loop(self, X, y):
    156         X_train, X_valid, y_train, y_valid = self.train_test_split(
--> 157             X, y, self.eval_size)
    158 
    159         on_epoch_finished = self.on_epoch_finished

C:\bin\Anaconda\lib\site-packages\nolearn\lasagne.pyc in train_test_split(self, X, y, eval_size)
    260             kf = KFold(y.shape[0], 1. / eval_size)
    261         else:
--> 262             kf = StratifiedKFold(y, 1. / eval_size)
    263 
    264         train_indices, valid_indices = iter(kf).next()
```
Is there anything wrong in my settings?

**Comment by alexjc** [comment] 2015-04-26 11:33
I get something like this:

````
 Epoch  |  Train loss  |  Valid loss  |  Train / Val  |  Valid acc  |  Dur
--------|--------------|--------------|---------------|-------------|-------
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
     1  |    0.411886  |         nan  |          nan  |       nan%  |  1.2s
````

But it continues training...

**Comment by dnouri** [comment] 2015-04-26 15:42
@delphine108 Looks like your nolearn version is too old.  Take a look at this: https://github.com/dnouri/kfkd-tutorial/issues/16#issuecomment-95498152

I'll close this since @fmfn says the suggested fix works for him.

**Closed by dnouri** 2015-04-26 15:42 UTC
