### ISSUE TITLE
Getting Epoch number in BatchIterator subclass

### ISSUE THREAD

**Issue by msegala** [dnouri/nolearn#57] opened 2015-03-06 17:04 UTC
I was wondering if there is a way to get the current epoch number in a BatchIterator subclass?
The basic idea is I only want to perform data augmentations on the first 90% of epochs.
For example, assume we have 100 epochs AND had access to train_history:

class FlipBatchIterator(BatchIterator):
   epoch = train_history[-1]['epoch']
   def transform(self, Xb, yb):
      if epoch < 90:    
         Xb, yb = super(FlipBatchIterator, self).transform(Xb, yb)
      return Xb, yb

**Comment by dnouri** [comment] 2015-03-06 17:44
@cancan101 made a very similar suggestion in #36.  Your question seems to be another indicator that being able to access the `NeuralNet` instance inside the `BatchIterator` is really useful.  Until we get around to adding that, and change the `BatchIterator` interface, I'd suggest you try the solution from this comment: https://github.com/dnouri/nolearn/issues/36#issuecomment-73480614

**Comment by dnouri** [comment] 2015-03-06 17:45
Closing as duplicate of #36.

**Closed by dnouri** 2015-03-06 17:45 UTC
