### ISSUE TITLE
memory effiency

### ISSUE THREAD

**Issue by fayeshine** [dnouri/nolearn#209] opened 2016-01-31 11:11 UTC
I found nolearn model keep the training data in the memory, so when I train many models, it will eat up the memory resources very fast. I think nolearn model should release the training data after the training is done.

**Comment by fayeshine** [comment] 2016-02-03 10:28
@dnouri can you solve it?

**Comment by dnouri** [comment] 2016-02-03 18:27
The problem is the BatchIterators that are clinging on to X and y.  We could always delete those variables at the end of `__iter__`.  Manually deleting those variables should work as well: `del net.batch_iterator_train.X, net.batch_iterator_train.y` etc.

**Comment by fayeshine** [comment] 2016-02-04 02:54
@dnouri thanks, besides, another problem is:
        when I train a model, it always copy the training data, can we train the data in-place. If I have a training cost more than 50% percentage of memory,  there's no room for a copy.

**Comment by dnouri** [comment] 2016-02-04 03:04
@fayeshine Where is it copying training data?

**Comment by fayeshine** [comment] 2016-02-04 03:43
@dnouri , when I load data into a numpy array, it cost 16% memory, then when I start to train, it cost 32% memory, so I think it copy the training data in the memory.

**Comment by BenjaminBossan** [comment] 2016-02-06 11:21
I also sometimes observe that memory (both main and GPU) is not released. However, I'm not sure it is caused by the BatchIterator, since it also happening when I re-initialize the same model, which should erase any reference to the last BatchIterator.

Regarding @fayeshine's second problem, could it be related to either image augmentation or EarlyStopping?

**Comment by BenjaminBossan** [comment] 2016-02-13 12:31
I have another suspicion where memory could be waisted needlessly, namely in the `BatchIterator` when setting `shuffle=True`:

```
import numpy as np
from nolearn.lasagne import BatchIterator

X = np.arange(1000)

it0 = BatchIterator(128, shuffle=False)
it0(X)
id(X) == id(it0.X)  #  returns True

it1 = BatchIterator(128, shuffle=True)
it1(X)
id(X) == id(it1.X)  # returns False
```

@dnouri Do we want another implementation for shuffle that does not produce this effect?

**Comment by dnouri** [comment] 2016-03-25 18:56
@BenjaminBossan Essentially, instead of using `indices = self.random.permutation(np.arange(X0.shape[0]))` we'd have to do in-place shuffling twice, re-setting the seed between shuffles.  Is that what you're proposing?

**Comment by BenjaminBossan** [comment] 2016-03-25 20:51
I believe my comment was based on an earlier version of `BatchIterator`, is that possible? Before changing anything, we should first check whether this one makes a copy or not (both for arrays and dicts). If you want me to check it, I will when I have time.

**Comment by dnouri** [comment] 2016-03-25 20:53
Fancy indexing will definitely make a copy.  Your Feb 13 observation should still hold true.

**Comment by dnouri** [comment] 2016-03-25 21:55
@BenjaminBossan Your ['other suspicion' issue](https://github.com/dnouri/nolearn/issues/209#issuecomment-183658288) should be fixed with b4433b5.

**Comment by dnouri** [comment] 2016-03-26 02:15
@fayeshine Would you have a look and see if the issue is now fixed with the latest nolearn from master?

**Comment by dnouri** [comment] 2016-04-06 14:11
Closed due to inactivity.  I believe this issue has been resolved anyway.

**Closed by dnouri** 2016-04-06 14:11 UTC
