### ISSUE TITLE
Multiple network outputs

### ISSUE THREAD

**Issue by dudheit** [dnouri/nolearn#202] opened 2016-01-24 21:17 UTC
Is there any way to handle multiple output layers? I'd like to train a network where the first classification result is feed back into the network, e.g.:

    example_layer = lasagne.layers.InputLayer(inputs_layer, **params)
    
    ...
    
    classification_output = lasagne.layers.DenseLayer(example_layer, nonlinearity=lasagne.nonlinearities.softmax, **params2)
    
    ...

    another_output_layer = lasagne.layers.DenseLayer(classification_output, nonlinearity=lasagne.nonlinearities.softmax, **params3)
    
    return classification_output, another_output_layer

**Comment by cancan101** [comment] 2016-01-25 04:47
Duplicate of #158?

**Comment by dudheit314** [comment] 2016-01-25 08:00
Yes, I see, sorry for reopening the issue here. No workarounds for this so far?

**Comment by dnouri** [comment] 2016-03-11 02:37
Do you really need both as true outputs?  Or are you merely looking to attach a loss to both of these layers during training?  If the latter, then this can be done today by writing your own `objective` function.

**Comment by dudheit** [comment] 2016-03-11 13:24
No, I was really looking for two distinct outputs e.g. classification and pose estimation such that the network predicts the object class and the object rotation at the same time. But I was able to work around it using inheritance.

**Comment by dnouri** [comment] 2016-03-11 17:34
This is probably not ideal either, but would it work for you to use `net.get_output([out1, out2], X)` after training?

**Comment by dudheit** [comment] 2016-03-11 19:08
Well since I already found a solution and stopped working on it I can't quickly check whether it would work this way right now. I'll probably have a look on it in a few weeks when I start working on a different project.

**Comment by dnouri** [comment] 2016-03-11 19:16
It'd be interesting to see your solution based on inheritance, should you ever get around to extracting it.

**Comment by dudheit** [comment] 2016-03-12 15:55
I'll see whether I get chance to outline my solution here ...

**Comment by DanChianucci** [comment] 2016-07-21 14:20
I have a similar issue, which doesn't work even if I write my own objective.  I have a network which splits into two branches.  One branch outputs an image patch (NxCHxHxW), and the other outputs a class (NxCLS) , similar to the network shown below. 

```
   A
   B
 /  \
C    E
D    F
```
Since the NeuralNet takes a single Layer instance for its layers parameter, one of the branches is completely ignored.  For example, if I instantiate the NeuralNet with F as the layers param, then C and D are not placed into the `layers_` dictionary.  Consequently, I can't reference C or D from my objective function.


I have fixed this by slightly modifying the initialize_layers method, so that it loops over all Layer instances contained within self.layers, rather than only self.layers[0].  I can submit a pull request if this is of interest.

**Comment by cancan101** [comment] 2016-07-21 14:29
I would be interested to see a PR.

**Comment by dnouri** [comment] 2016-08-28 03:23
Feature implemented in #278 and merged.  Continuing in #284: Network.predict works with multi-outputs.

**Closed by dnouri** 2016-08-28 03:23 UTC
